services:
  - type: web
    name: flask-app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 why:app
    runtime: python
    plan: free
    region: oregon
    healthCheckPath: /health
